### ISSUE TITLE
Proposals about contents

### ISSUE THREAD

**Issue by arowM** [ababup1192/elm-handson1#1]
Good job! I love this slide.
The comments bellow is my proposals to enhance your nice contents.

## p2

* 「対象者のレベル・経験について」の話と「対象者の目的」の話が混ざっています
    * 「対象者のレベル・経験」で統一するなら、3つ目は「関数型に不慣れな方」の方が適切です
    * あるいは3つ目はページを分ける必要があると思います
* 条件がORなのかANDなのか明記した方がいいと思います。
    * たとえばフロントエンド開発を普段からしているけどElmについて一切知らない人はターゲットでしょうか？
* 「関数型に易しく入門したい」という目的か「Elmを知りたい」という目的のどちらかに絞った方がいいと思います
    * どちらかに絞らないとどちらの目的にとっても良くないものになってしまう可能性が高そうです

## p16

* 関数を紹介するなら、いさぎよくファイルに書いて elm-repl で import する方法も紹介したほうがよさそうです
    * このあと `let` 式や `case` 式の紹介をするときとかも無理がある感じがするので。。。

## p32

* パターンマッチの前に `type` での型定義を紹介(Union type はまだ紹介しない)してもいいかもしれません
    * いきなり `Maybe a` がでてきても素養がある人にしかわからないと思うので
    * たぶん「 `type alias` ではカバーしきれない2つの用途」として説明できる
        * 「`type alias` では型安全じゃないけど、 `type Name = Name String` で安全にできるよ」
        * 「`type Unvelified x = Unvelified x` みたいに型変数をつけることができるよ」
            * (現状では、型変数が p36 でいきなり使われてる)

## p38

* Haskellの記法が混じってしまっています
* 型変数を使った例をこのページ以前であつかう必要があると思います
    * e.g., `type Point x y = Point x y`
* あえて再帰的データ型を紹介する必要はないかもしれません
    * 理由1: 自分で再帰的データ型を定義することはElmではほとんどないから
    * 理由2: ここで脱落者を増やしてしまうよりも、他に伝えたほうがいい内容がありそうだから
    * 「関数型に易しく入門したい方」をターゲットにするかしないかで変わるので、ハンズオンの方針によると思います

**Comment by ababup1192** [comment]
修正しました！
